services:
  db:
    image: mysql:8.0
    container_name: echoes_db
    restart: always
    environment:
      MYSQL_DATABASE: echoes
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.2
    container_name: echoes_redis
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: echoes_app
    restart: always
    args:
      KEYSTORE_PATH: ${KEYSTORE_PATH}
    depends_on:
      - db
      - redis
    ports:
      - "${APP_PORT:-443}:${SERVER_PORT:-443}"
    volumes:
      - ./certs:/app/certs
      - ./keystore.p12:/app/keystore.p12
    environment:
      # Mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/echoes
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}

      # Redis
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}

      # Server
      SERVER_PORT: ${SERVER_PORT:-443}
      USE_SSL: ${USE_SSL:-false}

      # SSL
      SERVER_SSL_KEY_STORE: /app/keystore.p12
      SERVER_SSL_KEY_STORE_PASSWORD: ${SSL_KEYSTORE_PASSWORD}
      SERVER_SSL_KEY_ALIAS: ${SSL_ALIAS}
      SERVER_SSL_KEY_STORE_TYPE: ${SSL_KEYSTORE_TYPE}

      # E-mail
      SPRING_MAIL_HOST: ${EMAIL_HOST}
      SPRING_MAIL_PORT: ${EMAIL_PORT}
      SPRING_MAIL_USERNAME: ${EMAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${EMAIL_PASSWORD}

      # API
      API_SMTP_TOKEN: ${API_KEY}
      API_SECURITY_TOKEN_SECRET: ${JWT_SECRET}
      TWOFACTOR_PROVIDER: ${TWO_FACTOR_PROVIDER}

      # JPA
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"

volumes:
  mysql_data:
  redis_data:
